### ISSUE TITLE
Question about this plugin

### ISSUE THREAD

**Issue by sondoha** [vietartisans/generator-va-wpplugin#1]
So we will have another repository named `sample-plugin`, should it merge to this one? Or we can use both?

@duyngha

**Comment by duyngha** [comment]
@sondoha cai `sample-plugin` e dinh dung de tong hop mot mau so chung cho plugin minh hay su dung cho cac du an wp. Bao gom thong nhat cau truc thu muc, cac file core co dinh, namespace... No se la cai khung xuong cua `generator-va-wpplugin`. Vi hien tai cai `generator-va-wpplugin` van chua trien khai thuc te dc vi gap phai mot so loi.

**Comment by sondoha** [comment]
Anh moi push ben repository do. Anh em minh cung nhau update cac chuc nang chung nhat cho plugin do nhe. Viet readme len ke hoach roadmap truoc khi thuc thi

@duyngha

**Comment by sondoha** [comment]
Ben do ngon thi minh copy khung qua ben nay @duyngha

**Comment by duyngha** [comment]
@sondoha e dang tong hop lai cac module. Ben nay tam thoi minh pause. Ben kia tong hop xong e se update sang ben nay de push len NPM.

**Comment by sondoha** [comment]
Hien tai anh dang thay minh load het cac module trong `loadModules()` load het cac module minh co trong 1 luc, dieu nay la khong can thiet. Anh em minh se ban bac cu the hon ve cai nay sau nhe.

@duyngha
